### ISSUE TITLE
Question about code implement

### ISSUE THREAD

**Issue by IvanFei** [DengPingFan/E-measure#1]
Hi, @DengPingFan 

Nice idea about binary foreground map measure.

There are one problem when I read  your code.

when calculate the enhanced alignment score, your code divide `w*h - 1`. Why minus 1? It doesn't match with the paper. 

code: 
`
score = sum(enhanced_matrix(:))./(w*h - 1 + eps);
`

**Comment by DengPingFan** [comment]
Hi, It's motivated by the equation of (11) in SSIM (Image Quality Assessment: From Error Visibility to Structural Similarity, TIP 2014) paper. It's just a implementation details. You can also change it as w*h + eps




------------------ 原始邮件 ------------------
发件人: "fei"<notifications@github.com>; 
发送时间: 2019年9月12日(星期四) 中午12:23
收件人: "DengPingFan/E-measure"<E-measure@noreply.github.com>; 
抄送: "Deng-Ping Fan"<381620505@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: [DengPingFan/E-measure] Question about code implement (#1)




Hi, @DengPingFan
 
Nice idea about binary foreground map measure.
 
There are one problem when I read  your code.
 
when calculate the enhanced alignment score, your code divide w*h - 1. Why minus 1? It doesn't match with the paper.
 
code:
 score = sum(enhanced_matrix(:))./(w*h - 1 + eps);

**Comment by IvanFei** [comment]
@DengPingFan 
Ok, I got it. 
Thank you for your careful answer. 
 
best wishes.
